### ISSUE TITLE
Allow a specific format to be specified

### ISSUE THREAD

**Issue by petedmarsh** [closeio/ciso8601#20]
I would like to be able to specify a specific format that a date/time must match to be considered valid, something like:

```python
ciso.parse_datetime('2016-11-16T12:34:56.789', '%Y-%m-%dT%H:%M:%S.%f')
#or
ciso_parse_datetime('2016-11-16T12:34:56.789', ciso.DATE_TIME_WITH_MICROSECONDS)
```

Since this is a library for parsing ISO8601 date/times I think it would make sense to limit this to a strict set of formats (I do not want to be able to parse any arbitrary format).

This makes it easier to be strict on the format of date accepted for APIs etc.

**Comment by thomasst** [comment]
Thanks for the suggestion. If there's just a set of formats we need to support, I'd prefer the second variant with the constants. Feel free to submit a PR!

**Comment by movermeyer** [comment]
It seems that you are asking for an additional validation check that happens either:

- before the parse
-  or during the parse 
 
As a caller of `ciso8601`, you don't really care which it is.

IMO, `ciso8601` will never be an arbitrary datetime parser, so it wouldn't do this validation as part of the parse itself.

It would be possible to do two passes:

1. Use a regex to validate the the string matches the desired format
2. If it does, then parse it using `parse_datetime`.

It feels to me that the first stage is something that is better suited to do inside the caller's code instead of within `ciso8601`.

IMO, `ciso8601` will implement the spec. If the caller has a requirement for "stricter than ISO8601/RFC 3339" validation, then that belongs in some custom validation code the caller implements.
